### PR TITLE
Port to python3

### PR DESCRIPTION
**Pull request by fenrus75**

### CODE REVIEW

**Comment by mbelluzzo** [comment]
:+1:

**Comment by fenrus75** [comment]
ping?

**Comment by tebrandt** [comment]
The changes are significantly more complicated than that, many of the libraries have changed and require code rewrite. I already added the basic changes (to prints and to remove the string library) in master. I don't have time yet to convert the whole thing as it's in constant flux.

**Comment by tebrandt** [comment]
update, I'm almost done with a conversion that will allow it to run on both python2 and python3, should be ready in a couple weeks (end of June).

**Pull request closed without merging**
